services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${LOCAL_DB_PASSWORD}
      MYSQL_DATABASE: local_etl_db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  etl:
    build: .
    env_file: 
      - .env  # Explicitly load environment variables from the .env file
    environment:
      LOCAL_DB_HOST: mysql_db
      LOCAL_DB_PORT: 3306  # Override DB_HOST to use the service name in Docker network
    depends_on:
      mysql_db:
        condition: service_healthy